name: Semgrep SAST

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo hello
